### ISSUE TITLE
Läuft nicht mehr in IPS 7.0

### ISSUE THREAD

**Issue by ThomasW69** [jotata/SymconJoTKPP#1]
Das Modul verweigert in IPS7.0 komplett den Dienst. Es lässt sich noch nicht mal das Konfigurationsformular aufrufen.

**Comment by ThomasW69** [comment]
Die Zeile 164             $JSON = str_replace("\"$search\"", $replace, $JSON);
in JoT_Traits.php löst in PHP8  den folgenden Fehler aus:

03.07.2023, 17:11:14 | InstanceManager | Kann Schnittstellen-Instanz nicht erstellen:
Fatal error: Uncaught TypeError: str_replace(): Argument #2 ($replace) must be of type array|string, int given in /mnt/data/symcon/modules/.store/ch.tanner.jot.kpp/libs/JoT_Traits.php:164
Stack trace:
#0 /mnt/data/symcon/modules/.store/ch.tanner.jot.kpp/libs/JoT_Traits.php(164): str_replace(‚„$VT_Float“‘, 2, ‚[\n {\n …‘)
#1 /mnt/data/symcon/modules/.store/ch.tanner.jot.kpp/libs/JoT_Traits.php(37): JoTKPP->GetJSONwithVariables(‚/mnt/data/symco…‘, Array)
#2 /mnt/data/symcon/modules/.store/ch.tanner.jot.kpp/JoTKPP/module.php(41): JoTKPP->ConfigProfiles(‚/mnt/data/symco…‘, Array)
#3 /-(3): JoTKPP->Create()
#4 {main}
thrown in /mnt/data/symcon/modules/.store/ch.tanner.jot.kpp/libs/JoT_Traits.php on line 164

**Comment by jotata** [comment]
Ist in V2.3 gefixt
